### ISSUE TITLE
Install MongoDB and uwsgi?

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-demo#6]

**Comment by mohierf** [comment]
It is not up to this doc to explain how to install Mongo, but there is still some information about it:
```
# Alignak backend
    # You need to have a running Mongo database.
    # See the Alignak backend installation procedure if you need to set one up and running (http://alignak-backend.readthedocs.io/en/develop/install.html)
    sudo pip install alignak-backend
```
The Alignak backend installation gives an excerpt of an installation but invite to browse the Mongo DB site ... and I think that it is enough because installing Mongo is different from one version to another :wink: 

For uwsgi, is is installed automatically as a dependency of the Alignak backend. Nothing more to say about it :wink:
